name: flutter_app8
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
  #  shared_preferences: '>=0.5.12+4 <2.0.0'

  html2md: '>=1.20.1 <2.0.0'
dependencies:
  flutter_svg: ^0.21.0-nullsafety.0 #^0.19.0
  fluttertoast:   8.0.0-nullsafety.0
  dio: ^4.0.0




  moor_flutter: ^4.0.0
  # device_preview: ^0.7.1



  cached_network_image: ^3.0.0
  carousel_slider: 4.0.0-nullsafety.0
  connectivity:  ^3.0.3
  share_plus: ^2.1.2
  shared_preferences: ^2.0.5 # 2.0.0-nullsafety
  json_annotation: ^4.0.1
  url_launcher: ^6.0.3
  webview_flutter: 2.0.0-nullsafety.5
  html2md: ^1.0.1
  responsive_framework: ^0.1.0
  #dio_http_cache: ^0.2.11
  dio_cache_interceptor: ^2.0.0
  flutter_markdown: ^0.6.1
  sqlite3_flutter_libs: ^0.3.0
  hive: ^2.0.3
  hive_flutter: ^1.0.0
  path_provider: ^2.0.0

  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2


  provider: 5.0.0 #-nullsafety.3 #^4.3.3 #
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  overlay_support: 1.2.0-nullsafety.0
  #flutter_icons: ^1.1.0
  fluttericon: ^2.0.0
  font_awesome_flutter: ^9.0.0
  infinite_scroll_pagination: ^3.0.1
  search_page: ^2.0.0
  steps_indicator: ^1.3.0

  awesome_dialog: 2.0.0-nullsafety.1
  injectable: ^1.2.2

  device_preview: ^0.7.0
  flutter_deep_linking: ^0.2.0
  uni_links: ^0.5.1


  flutter_launcher_icons: "^0.9.0"


dev_dependencies:
  build_runner: ^1.12.2
  hive_generator: ^1.0.1



flutter_icons:
  image_path: "assets/redsea2.png"
  android: true
  ios: true
  flutter_test:
    sdk: flutter
#  integration_test:
#    sdk: flutter






# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - images/arabic2.png
      - images/arabs.png
      - images/arab.jpg
      - images/arb.png
      - images/account_img.jpeg
      - images/user.png
      - images/full_logo.svg
      - images/eng.svg
      - images/egl.png
      - images/ads1.jpg
      - images/ads2.jpg
      - images/ads3.jpg
      - images/ads44.jpg
      - images/ads5.jpg
      - images/ads6.jpg
      - images/splash.jpeg





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: lib/fonts/MyFlutterApp.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
