import 'package:flutter/material.dart';
import 'package:flutter_app8/generated/l10n.dart';
import 'package:flutter_app8/values/myApplication.dart';
import 'package:intl/intl.dart';
const String dataBoxName = "productData";
const String dataBoxNameFavs = "productDataFavs";
const String dataBoxNameUser = "userDataHive";
const String dataBoxNameCacheCats = "HiveCacheCats";
const String dataBoxNameCacheProductsCats = "HiveCacheProductsCats";
const String dataBoxNameCacheProducts = "HiveCacheProducts";

/*//Strings
 String email = S.of(context).email;
 String emptyField = S.of(context).emptyField;
 String noInternet = S.of(context).noInternet;
 String wrongCredentials = S.of(context).wrongEmailOrPass;
 String slowInternet = S.of(context).slowInternet;
 String connectError = S.of(context).timeOut;
 String dupEmail = S.of(context).dubEmail;
 String shortPass = S.of(context).shortPass;
 String dupPhone = S.of(context).dubPhone;
 String diffPasses = S.of(context).diffPasses;
 String invEmail = S.of(context).invEmail;
 String password = S.of(context).password;
 String confirmPassword = S.of(context).confirmPassword;
 String name = S.of(context).name;
 String lName = S.of(context).lName;
 String phone = S.of(context).phone;
 String address = S.of(context).address;
 String login = S.of(context).login;
 String update = S.of(context).update;
 String signed = S.of(context).signed;
 String passUpdated = S.of(context).PassUpdated;
 String profileUpdated = S.of(context).profileUpdated;
 String register = S.of(context).register;
 String loginLabel = S.of(context).loginLabel;
 String editPass = S.of(context).editPass;
 String editProfile = S.of(context).editProfile;
 String registerLabel = S.of(context).registerLabel;
 String cartAdd = S.of(context).cartAdd;
 String stShopping = S.of(context).stShopping;
 String swiToBrw = S.of(context).swiToBrw;
 String stShopDesc = S.of(context).stShopDesc;
 String fillIn = S.of(context).fillIn;
 String home = S.of(context).home;
 String cats = S.of(context).cats;
 String account = S.of(context).account;
 String country = S.of(context).country;
 String cart = S.of(context).cart;
 String cash = S.of(context).cash;
 String checkOut = S.of(context).checkOut;
 String online = S.of(context).online;
 String quantity = S.of(context).quantity;
 String governorate = S.of(context).governorate;
 String city = S.of(context).city;
 String shipper = S.of(context).shipper;
 String perData = S.of(context).perData;
 String payment = S.of(context).payment;
 String orders = S.of(context).orders;
 String wish = S.of(context).wish;
 String lang = S.of(context).lang;
 String signOut = S.of(context).signOut;*/
const String tokenKey = "tokenPref";
 /*String searchHere = S.of(context).search;*/

//Dimensions
const textFieldContentPaddingHorizontal = 30.0;
const textFieldContentPaddingVertical = 16.0;
const textRegisterLabelPadding = 16.0;
const textLabelSize = 16.0;
const scrollBarRadius = 8.0;
const textDialogueTitleSize = 20.0;
const textFieldsDivider = 40;
const toolbarHeight = 70.0;
const textFieldButtonDivider = 20;
const textFieldButtonDividerLogin = 15;
const registerTextFieldLabelDivider = 30;
const loginTextFieldLabelDivider = 20;
const registerTopViewHeight = 25;
const columnRegisterBorderRadius = 30.0;
const loginProgressDivider = 15;
const accountTextSize = 14.0;
const accountDividerBy = 1.5;
const RateTextDividerBy = 22;
//Colors
//const Color colorPrimary = Color(0xFF8B80D8);
const Color colorPrimary = Colors.black;
const Color colorSemiWhite = Color(0x77ffffff);
const Color colorSemiWhite2 = Color(0x44ffffff);
const Color colorBorder = Colors.black54;

const Color colorAccountIcon = Colors.grey;
const Color colorAccountFocus = colorPrimary;
